export interface ProductVariant {
  size: string;
  inventory: number;
}

export interface Product {
  id: string;
  title: string;
  handle: string;
  description: string;
  price: number;
  collection: 'tees' | 'hoodies' | 'stickers' | 'cards' | 'toys';
  images: string[];
  variants: ProductVariant[];
}

const generateInventory = () => Math.floor(Math.random() * 151);

const apparelVariants = (): ProductVariant[] => [
  { size: 'S', inventory: generateInventory() },
  { size: 'M', inventory: generateInventory() },
  { size: 'L', inventory: generateInventory() },
  { size: 'XL', inventory: generateInventory() },
  { size: 'XXL', inventory: generateInventory() },
];

const accessoryVariants = (): ProductVariant[] => [
  { size: 'OS', inventory: generateInventory() }
];

export const HAKI_DROP_PRODUCTS: Product[] = [
  // ---------------------------------------------------------
  // 1. THE DRUMS OF LIBERATION LINE (TEES)
  // ---------------------------------------------------------
  {
    id: 'gid://shopify/Product/1001',
    title: 'DRUMS OF LIBERATION // Oversized Tee',
    handle: 'drums-of-liberation-oversized-tee',
    description: 'Vintage-washed charcoal black tee with a bold chest typography layout.',
    price: 55,
    collection: 'tees',
    images: ['/images/products/drums-of-liberation-oversized-tee-1.jpg'],
    variants: apparelVariants(),
  },
  {
    id: 'gid://shopify/Product/1002',
    title: 'SUN GOD // Sketch Tee',
    handle: 'sun-god-sketch-tee',
    description: 'Off-white mid-weight luxury cotton with a rough charcoal sketch design of Luffy laughing.',
    price: 45,
    collection: 'tees',
    images: ['/images/products/sun-god-sketch-tee-1.jpg'],
    variants: apparelVariants(),
  },
  {
    id: 'gid://shopify/Product/1003',
    title: 'HAKI CRACKLE // Acid-Wash Tee',
    handle: 'haki-crackle-acid-wash-tee',
    description: 'Purple-and-black cloud-dye pattern tee with a high-density rubber print icon.',
    price: 50,
    collection: 'tees',
    images: ['/images/products/haki-crackle-acid-wash-tee-1.jpg'],
    variants: apparelVariants(),
  },
  {
    id: 'gid://shopify/Product/1004',
    title: 'WANOKUNI // Typography Long-Sleeve',
    handle: 'wanokuni-typography-long-sleeve',
    description: 'Heavyweight long-sleeve cotton tee featuring vertical arm sleeve canvas text prints.',
    price: 65,
    collection: 'tees',
    images: ['/images/products/wanokuni-typography-long-sleeve-1.jpg'],
    variants: apparelVariants(),
  },
  {
    id: 'gid://shopify/Product/1005',
    title: 'MONKEY D. // Legacy Box Logo Tee',
    handle: 'monkey-d-legacy-box-logo-tee',
    description: 'Minimalist black luxury blank tee with ultra-clean white-and-red box logo stitching.',
    price: 45,
    collection: 'tees',
    images: ['/images/products/monkey-d-legacy-box-logo-tee-1.jpg'],
    variants: apparelVariants(),
  },
  {
    id: 'gid://shopify/Product/1006',
    title: 'AWAKENING // Drop-Shoulder Tee',
    handle: 'awakening-drop-shoulder-tee',
    description: 'Slate gray relaxed fit knit jersey with split-hem side vents.',
    price: 52,
    collection: 'tees',
    images: ['/images/products/awakening-drop-shoulder-tee-1.jpg'],
    variants: apparelVariants(),
  },
  {
    id: 'gid://shopify/Product/1007',
    title: 'WILL OF D // Minimalist Pocket Tee',
    handle: 'will-of-d-minimalist-pocket-tee',
    description: 'Sandwashed pocket tee featuring a subtle embroidered semi-circle layout on the pocket.',
    price: 40,
    collection: 'tees',
    images: ['/images/products/will-of-d-minimalist-pocket-tee-1.jpg'],
    variants: apparelVariants(),
  },
  {
    id: 'gid://shopify/Product/1008',
    title: "EMPEROR'S MIGHT // Graphic Tee",
    handle: 'emperors-might-graphic-tee',
    description: "Deep indigo heavy wash jersey with a geometric Conqueror's aura print.",
    price: 48,
    collection: 'tees',
    images: ['/images/products/emperors-might-graphic-tee-1.jpg'],
    variants: apparelVariants(),
  },
  {
    id: 'gid://shopify/Product/1009',
    title: 'LIBERATOR // Heavy-Knit Tee',
    handle: 'liberator-heavy-knit-tee',
    description: 'Pure chalk white featuring a premium tonal raised puff print on the shoulder blades.',
    price: 58,
    collection: 'tees',
    images: ['/images/products/liberator-heavy-knit-tee-1.jpg'],
    variants: apparelVariants(),
  },
  {
    id: 'gid://shopify/Product/1010',
    title: 'PIRATE KING // Split Panel Tee',
    handle: 'pirate-king-split-panel-tee',
    description: 'Half-black, half-white structural panels stitched down the center.',
    price: 55,
    collection: 'tees',
    images: ['/images/products/pirate-king-split-panel-tee-1.jpg'],
    variants: apparelVariants(),
  },

  // ---------------------------------------------------------
  // 2. THE WANO OVERDRIVE LAYER (HOODIES & OUTERWEAR)
  // ---------------------------------------------------------
  {
    id: 'gid://shopify/Product/2001',
    title: 'NIKA // The Liberator Heavyweight Hoodie',
    handle: 'nika-liberator-heavyweight-hoodie',
    description: '450GSM French Terry cotton in bone white with purple Haki lightning embroidery.',
    price: 120,
    collection: 'hoodies',
    images: ['/images/products/nika-liberator-heavyweight-hoodie-1.jpg'],
    variants: apparelVariants(),
  },
  {
    id: 'gid://shopify/Product/2002',
    title: 'GEAR FIFTH // Coach Windbreaker',
    handle: 'gear-fifth-coach-windbreaker',
    description: 'Water-resistant matte white ripstop nylon featuring a hidden reflective Nika cloud pattern.',
    price: 95,
    collection: 'hoodies',
    images: ['/images/products/gear-fifth-coach-windbreaker-1.jpg'],
    variants: apparelVariants(),
  },
  {
    id: 'gid://shopify/Product/2003',
    title: 'ONIGASHIMA // Distressed Denim Jacket',
    handle: 'onigashima-distressed-denim-jacket',
    description: 'Acid-washed black denim with a massive back-panel woven tapestry patch.',
    price: 150,
    collection: 'hoodies',
    images: ['/images/products/onigashima-distressed-denim-jacket-1.jpg'],
    variants: apparelVariants(),
  },
  {
    id: 'gid://shopify/Product/2004',
    title: 'SUPREME HAKI // Bomber Jacket',
    handle: 'supreme-haki-bomber-jacket',
    description: 'Satin-lined flight jacket featuring purple-and-black structural crackle stitching.',
    price: 165,
    collection: 'hoodies',
    images: ['/images/products/supreme-haki-bomber-jacket-1.jpg'],
    variants: apparelVariants(),
  },
  {
    id: 'gid://shopify/Product/2005',
    title: 'CONQUEROR // Velvet Puffer',
    handle: 'conqueror-velvet-puffer',
    description: 'Deep plum velvet oversized crop puffer jacket with thermal heat-retention lining.',
    price: 180,
    collection: 'hoodies',
    images: ['/images/products/conqueror-velvet-puffer-1.jpg'],
    variants: apparelVariants(),
  },
  {
    id: 'gid://shopify/Product/2006',
    title: 'JOYBOY // Knit Cardigan',
    handle: 'joyboy-knit-cardigan',
    description: 'Heavy mohair knit cardigan with cloud-white panel patterns and minimalist resin buttons.',
    price: 110,
    collection: 'hoodies',
    images: ['/images/products/joyboy-knit-cardigan-1.jpg'],
    variants: apparelVariants(),
  },
  {
    id: 'gid://shopify/Product/2007',
    title: 'RED FORCE // Varsity Jacket',
    handle: 'red-force-varsity-jacket',
    description: 'Wool body with premium white leather sleeves and custom Chenille "Haki Drop" chest lettering.',
    price: 195,
    collection: 'hoodies',
    images: ['/images/products/red-force-varsity-jacket-1.jpg'],
    variants: apparelVariants(),
  },
  {
    id: 'gid://shopify/Product/2008',
    title: 'ROGER // Inherited Will Anorak',
    handle: 'roger-inherited-will-anorak',
    description: 'Crimson technical windbreaker with a golden embroidery print of the legendary Loguetown coordinates.',
    price: 130,
    collection: 'hoodies',
    images: ['/images/products/roger-inherited-will-anorak-1.jpg'],
    variants: apparelVariants(),
  },
  {
    id: 'gid://shopify/Product/2009',
    title: 'RAISED IN WANO // Kimono Cloak',
    handle: 'raised-in-wano-kimono-cloak',
    description: 'Modern streetwear tech-wear haori with a stylized, flowing purple wind trail design.',
    price: 85,
    collection: 'hoodies',
    images: ['/images/products/raised-in-wano-kimono-cloak-1.jpg'],
    variants: apparelVariants(),
  },
  {
    id: 'gid://shopify/Product/2010',
    title: 'EMPEROR // Tech-Fleece Zip',
    handle: 'emperor-tech-fleece-zip',
    description: 'Double-knit lightweight performance zip-up hoodie featuring blacked-out heat-sealed tactical zippers.',
    price: 115,
    collection: 'hoodies',
    images: ['/images/products/emperor-tech-fleece-zip-1.jpg'],
    variants: apparelVariants(),
  },

  // ---------------------------------------------------------
  // 3. SPIRITUAL PRESSURE ACCESSORIES (STICKERS & DECALS)
  // ---------------------------------------------------------
  {
    id: 'gid://shopify/Product/3001',
    title: 'GEAR 5 REVEAL // Holographic Sticker',
    handle: 'gear-5-reveal-holographic-sticker',
    description: 'Laser-cut holographic sticker reflecting shifting purples and chromes.',
    price: 8,
    collection: 'stickers',
    images: ['/images/products/gear-5-reveal-holographic-sticker-1.jpg'],
    variants: accessoryVariants(),
  },
  {
    id: 'gid://shopify/Product/3002',
    title: 'HAKI CRACKLE // Die-Cut Vinyl Decal',
    handle: 'haki-crackle-die-cut-vinyl-decal',
    description: 'Weatherproof pitch-black and deep purple lightning vinyl decal designed for vehicles or laptops.',
    price: 6,
    collection: 'stickers',
    images: ['/images/products/haki-crackle-die-cut-vinyl-decal-1.jpg'],
    variants: accessoryVariants(),
  },
  {
    id: 'gid://shopify/Product/3003',
    title: 'DRUMS OF LIBERATION // Slap Sticker',
    handle: 'drums-of-liberation-slap-sticker',
    description: 'Traditional Japanese city street-style vinyl slap sticker containing high-gloss kanji.',
    price: 7,
    collection: 'stickers',
    images: ['/images/products/drums-of-liberation-slap-sticker-1.jpg'],
    variants: accessoryVariants(),
  },
  {
    id: 'gid://shopify/Product/3004',
    title: "WANO ARC // Collector's Sticker Pack",
    handle: 'wano-arc-collectors-sticker-pack',
    description: 'A premium 10-piece matte-finish sticker set featuring character crest silhouettes.',
    price: 25,
    collection: 'stickers',
    images: ['/images/products/wano-arc-collectors-sticker-pack-1.jpg'],
    variants: accessoryVariants(),
  },
  {
    id: 'gid://shopify/Product/3005',
    title: 'NIKA CLOUD // Mini Sticker Sheet',
    handle: 'nika-cloud-mini-sticker-sheet',
    description: "A sheet of 15 translucent, textured sticker elements shaped like Nika's floating smoke scarves.",
    price: 12,
    collection: 'stickers',
    images: ['/images/products/nika-cloud-mini-sticker-sheet-1.jpg'],
    variants: accessoryVariants(),
  },
  {
    id: 'gid://shopify/Product/3006',
    title: 'WANOKUNI // Bumper Sticker',
    handle: 'wanokuni-bumper-sticker',
    description: 'Long format high-visibility warning style text decal in bold red and white.',
    price: 9,
    collection: 'stickers',
    images: ['/images/products/wanokuni-bumper-sticker-1.jpg'],
    variants: accessoryVariants(),
  },
  {
    id: 'gid://shopify/Product/3007',
    title: 'WILL OF D // Minimalist Emblem Decal',
    handle: 'will-of-d-minimalist-emblem-decal',
    description: 'Subtle, semi-reflective silver metallic skin sticker.',
    price: 5,
    collection: 'stickers',
    images: ['/images/products/will-of-d-minimalist-emblem-decal-1.jpg'],
    variants: accessoryVariants(),
  },
  {
    id: 'gid://shopify/Product/3008',
    title: "CONQUEROR'S LIGHTNING // Glow Decal",
    handle: 'conquerors-lightning-glow-decal',
    description: 'Photoluminescent sticker that charges under light to glow vibrant neon purple in total darkness.',
    price: 10,
    collection: 'stickers',
    images: ['/images/products/conquerors-lightning-glow-decal-1.jpg'],
    variants: accessoryVariants(),
  },
  {
    id: 'gid://shopify/Product/3009',
    title: 'JOYBOY // Retro Chibi Decal',
    handle: 'joyboy-retro-chibi-decal',
    description: 'Comic caricature style cut-out layer utilizing premium UV-resistant ink coatings.',
    price: 6,
    collection: 'stickers',
    images: ['/images/products/joyboy-retro-chibi-decal-1.jpg'],
    variants: accessoryVariants(),
  },
  {
    id: 'gid://shopify/Product/3010',
    title: 'HAKI DROP // Holographic Box Logo Pack',
    handle: 'haki-drop-holographic-box-logo-pack',
    description: 'A 5-piece luxury bundle of changing iridescent brand logo configurations.',
    price: 15,
    collection: 'stickers',
    images: ['/images/products/haki-drop-holographic-box-logo-pack-1.jpg'],
    variants: accessoryVariants(),
  },

  // ---------------------------------------------------------
  // 4. THE MARIEJOIS ARCHIVE (TRADING CARDS & PREMIUM PRINTS)
  // ---------------------------------------------------------
  {
    id: 'gid://shopify/Product/4001',
    title: 'NIKA THE SUN GOD // Gold Foil Art Print',
    handle: 'nika-the-sun-god-gold-foil-art-print',
    description: 'A premium 12x18 heavy cardstock print accented with real metallic gold leafing layers.',
    price: 45,
    collection: 'cards',
    images: ['/images/products/nika-the-sun-god-gold-foil-art-print-1.jpg'],
    variants: accessoryVariants(),
  },
  {
    id: 'gid://shopify/Product/4002',
    title: 'EMPEROR LUFFY // Chrome-Foil Trading Card',
    handle: 'emperor-luffy-chrome-foil-trading-card',
    description: "Limited-edition custom collector's metal card displaying deep etched serial numbers.",
    price: 20,
    collection: 'cards',
    images: ['/images/products/emperor-luffy-chrome-foil-trading-card-1.jpg'],
    variants: accessoryVariants(),
  },
  {
    id: 'gid://shopify/Product/4003',
    title: 'WANO ARC CLIMAX // Lenticular 3D Print',
    handle: 'wano-arc-climax-lenticular-3d-print',
    description: 'A poster print shifting dynamically between Base Form Luffy and Gear 5 layout fields upon viewing angle.',
    price: 55,
    collection: 'cards',
    images: ['/images/products/wano-arc-climax-lenticular-3d-print-1.jpg'],
    variants: accessoryVariants(),
  },
  {
    id: 'gid://shopify/Product/4004',
    title: 'THE FOUR EMPERORS // Matte Art Poster',
    handle: 'the-four-emperors-matte-art-poster',
    description: 'Minimalist black-and-white print tracking the silhouette typography of the Yonko.',
    price: 35,
    collection: 'cards',
    images: ['/images/products/the-four-emperors-matte-art-poster-1.jpg'],
    variants: accessoryVariants(),
  },
  {
    id: 'gid://shopify/Product/4005',
    title: 'DRUMS OF LIBERATION // Sound-Wave Print',
    handle: 'drums-of-liberation-sound-wave-print',
    description: 'High-gloss graphic visualization map of the drums heartbeat vector typography.',
    price: 40,
    collection: 'cards',
    images: ['/images/products/drums-of-liberation-sound-wave-print-1.jpg'],
    variants: accessoryVariants(),
  },
  {
    id: 'gid://shopify/Product/4006',
    title: 'PIRATE KING // Canvas Wall Scroll',
    handle: 'pirate-king-canvas-wall-scroll',
    description: 'Traditional woven canvas fabric scroll hanging from modular solid dark walnut wood bars.',
    price: 65,
    collection: 'cards',
    images: ['/images/products/pirate-king-canvas-wall-scroll-1.jpg'],
    variants: accessoryVariants(),
  },
  {
    id: 'gid://shopify/Product/4007',
    title: "CONQUEROR'S IMPACT // Holo Illustration",
    handle: 'conquerors-impact-holo-illustration',
    description: 'Iridescent card layout illustrating the initial clash breaking open sky structures.',
    price: 30,
    collection: 'cards',
    images: ['/images/products/conquerors-impact-holo-illustration-1.jpg'],
    variants: accessoryVariants(),
  },
  {
    id: 'gid://shopify/Product/4008',
    title: 'WANOKUNI // Sketch Variant Print',
    handle: 'wanokuni-sketch-variant-print',
    description: 'Lithograph reproduction of rough development sketch panels from the Onigashima invasion mapping.',
    price: 25,
    collection: 'cards',
    images: ['/images/products/wanokuni-sketch-variant-print-1.jpg'],
    variants: accessoryVariants(),
  },
  {
    id: 'gid://shopify/Product/4009',
    title: 'WILL OF D // Secret Rare Card Fragment',
    handle: 'will-of-d-secret-rare-card-fragment',
    description: 'Textured premium collectible stock card framed inside a screw-down acrylic display block.',
    price: 15,
    collection: 'cards',
    images: ['/images/products/will-of-d-secret-rare-card-fragment-1.jpg'],
    variants: accessoryVariants(),
  },
  {
    id: 'gid://shopify/Product/4010',
    title: 'INHERITED WILL // Triple-Panel Display',
    handle: 'inherited-will-triple-panel-display',
    description: 'Triptych format set of three matching minimalist timeline art boards.',
    price: 90,
    collection: 'cards',
    images: ['/images/products/inherited-will-triple-panel-display-1.jpg'],
    variants: accessoryVariants(),
  },

  // ---------------------------------------------------------
  // 5. JOYBOY LAB (TOYS & HIGH-END COLLECTIBLES)
  // ---------------------------------------------------------
  {
    id: 'gid://shopify/Product/5001',
    title: 'GEAR 5 // Vinyl Designer Toy',
    handle: 'gear-5-vinyl-designer-toy',
    description: 'An 8-inch high-end soft vinyl art toy depicting Luffy bouncing with a clear smoky support stand base.',
    price: 110,
    collection: 'toys',
    images: ['/images/products/gear-5-vinyl-designer-toy-1.jpg'],
    variants: accessoryVariants(),
  },
  {
    id: 'gid://shopify/Product/5002',
    title: 'NIKA // Nendoroid-Scale Action Figure',
    handle: 'nika-nendoroid-scale-action-figure',
    description: 'Fully articulated modular action figure equipped with interchangeable dynamic faces and Haki lightning props.',
    price: 75,
    collection: 'toys',
    images: ['/images/products/nika-nendoroid-scale-action-figure-1.jpg'],
    variants: accessoryVariants(),
  },
  {
    id: 'gid://shopify/Product/5003',
    title: 'THE DRUMS // Electronic Desktop Drum Replica',
    handle: 'the-drums-electronic-desktop-drum-replica',
    description: 'A micro-prop that thumps out physical, bass-heavy vibrations and LED lighting flashes on button click.',
    price: 95,
    collection: 'toys',
    images: ['/images/products/the-drums-electronic-desktop-drum-replica-1.jpg'],
    variants: accessoryVariants(),
  },
  {
    id: 'gid://shopify/Product/5004',
    title: 'ONIGASHIMA // Brick Building Architecture Set',
    handle: 'onigashima-brick-building-architecture-set',
    description: 'An 1,200 piece advanced micro-brick kit to assemble the skull dome structure.',
    price: 145,
    collection: 'toys',
    images: ['/images/products/onigashima-brick-building-architecture-set-1.jpg'],
    variants: accessoryVariants(),
  },
  {
    id: 'gid://shopify/Product/5005',
    title: 'CONQUEROR // Custom Resinated Chess Set',
    handle: 'conqueror-custom-resinated-chess-set',
    description: 'High-end chess setup split between deep translucent purple and opaque bone-white custom figures.',
    price: 250,
    collection: 'toys',
    images: ['/images/products/conqueror-custom-resinated-chess-set-1.jpg'],
    variants: accessoryVariants(),
  },
  {
    id: 'gid://shopify/Product/5006',
    title: 'LUFFY GEAR 5 // Plush Plush Collectible',
    handle: 'luffy-gear-5-plush-plush-collectible',
    description: 'Oversized luxury plush doll sewn with super soft high-pile fleece hair layers.',
    price: 35,
    collection: 'toys',
    images: ['/images/products/luffy-gear-5-plush-plush-collectible-1.jpg'],
    variants: accessoryVariants(),
  },
  {
    id: 'gid://shopify/Product/5007',
    title: 'WANO ROOFTOP // Die-Cast Vehicle Match',
    handle: 'wano-rooftop-die-cast-vehicle-match',
    description: 'Scale down custom-painted matte black alloy container truck layout showcasing brand graphics.',
    price: 25,
    collection: 'toys',
    images: ['/images/products/wano-rooftop-die-cast-vehicle-match-1.jpg'],
    variants: accessoryVariants(),
  },
  {
    id: 'gid://shopify/Product/5008',
    title: 'HAKI COMPASS // Mechanical Gyro Spinner',
    handle: 'haki-compass-mechanical-gyro-spinner',
    description: 'Full-metal structural hand toy utilizing premium ceramic bearing rings for high spin durations.',
    price: 40,
    collection: 'toys',
    images: ['/images/products/haki-compass-mechanical-gyro-spinner-1.jpg'],
    variants: accessoryVariants(),
  },
  {
    id: 'gid://shopify/Product/5009',
    title: 'SUN GOD // Glowing Desktop Orb Lamp',
    handle: 'sun-god-glowing-desktop-orb-lamp',
    description: '3D laser-etched crystal sphere lamp casting custom lighting auras upwards.',
    price: 85,
    collection: 'toys',
    images: ['/images/products/sun-god-glowing-desktop-orb-lamp-1.jpg'],
    variants: accessoryVariants(),
  },
  {
    id: 'gid://shopify/Product/5010',
    title: 'MONKEY D. // Poseable Figma Masterpiece',
    handle: 'monkey-d-poseable-figma-masterpiece',
    description: "Collector's grade scale presentation figure detailed with wire-hemmed fabric clothing options.",
    price: 130,
    collection: 'toys',
    images: ['/images/products/monkey-d-poseable-figma-masterpiece-1.jpg'],
    variants: accessoryVariants(),
  }
];
